In [1]:
import pandas as pd
import numpy as np

In [2]:
pf = pd.read_csv("MYDATA copy.csv") #returns dataframe

In [3]:
pf

Name   Age  Gender   Country
0   John  25.0   Male,       USA
1  Alice  30.0  Female    Canada
2    Bob  35.0    Male       NaN
3   Jane  43.0     NaN       NaN
4   Mike  22.0    Male   Germany
5    Lic   NaN     NaN   Ireland
6    Kum   5.0  Female  Pakistan
7   Lora   NaN     NaN       NaN

In [5]:
pf['Gender'] = pf['Gender'].fillna(pf['Gender'].mode()[0])  # Fill with mode

In [6]:
pf

Name   Age  Gender   Country
0   John  25.0   Male,       USA
1  Alice  30.0  Female    Canada
2    Bob  35.0    Male       NaN
3   Jane  43.0  Female       NaN
4   Mike  22.0    Male   Germany
5    Lic   NaN  Female   Ireland
6    Kum   5.0  Female  Pakistan
7   Lora   NaN  Female       NaN

In [7]:
pf['Country'] = pf['Country'].fillna(pf['Country'].mode()[0])  # Fill with mode

In [8]:
pf

Name   Age  Gender   Country
0   John  25.0   Male,       USA
1  Alice  30.0  Female    Canada
2    Bob  35.0    Male    Canada
3   Jane  43.0  Female    Canada
4   Mike  22.0    Male   Germany
5    Lic   NaN  Female   Ireland
6    Kum   5.0  Female  Pakistan
7   Lora   NaN  Female    Canada

In [11]:
from sklearn.ensemble import RandomForestClassifier

# Assuming X contains features and y contains target variable

# Fit a Random Forest model to get feature importances
rf = RandomForestClassifier()
rf.fit(X, y)

# Get feature importances
feature_importances = rf.feature_importances_

NameError: name 'X' is not defined

In [14]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load the data into a DataFrame
data = {
    "order_id": [47856, 47857, 47858, 47859, 47860, 47861, 47862, 47863, 47864, 47865, 47866, 47867, 47868, 47869, 47870, 47871, 47872, 47873, 47874, 47875],
    "customer_id": [72, 63, 60, 69, 33, 76, 32, 25, 57, 66, 51, 43, 39, 37, 40, 62, 70, 62, 28, 63],
    "brand": ["Paul Reed Smith", "Fender", "Gibson", "Ibanez", "Jackson", "Schecter", "Epihone", "Rickenbacker", "G&L", "Charvel", "Fender", "Fender", "Epihone", "Paul Reed Smith", "Fender", "Jackson", "Paul Reed Smith", "Gibson", "Gibson", "Ibanez"],
    "model": ["Custom 22", "Stratocaster", "Les Paul Standard", "SA460QM-ABB", "Dinky", "Hellraiser", "Dot", "Model 330 12", "Fullerton", "Pro-Mod", "Stratocaster", "Stratocaster", "Dot", "SE", "Telecaster", "Dinky", "Custom 24", "Les Paul Standard", "Les Paul Studio", "SA460QM-ABB"],
    "colour": ["Black", "Fire Engine Red", "Sunburst", "Antique Brown Burst", "Yellow", "Purple", "Sunburst", "Blonde", "Yellow", "Green", "Seafoam Green", "Yellow", "Sunburst", "Blue", "Blue", "Silverburst", "Black Cherry", "Teaburst", "Yellow", "Antique Brown Burst"],
    "use_type_id": [3, 2, 1, 3, 3, 1, 1, 2, 1, 3, 1, 1, 3, 2, 2, 3, 2, 1, 1, 3]
}

df = pd.DataFrame(data)

# Select columns to normalize (excluding non-numeric columns)
columns_to_normalize = df.columns[df.dtypes != object]

# Apply Min-Max normalization
scaler = MinMaxScaler()
df[columns_to_normalize] = scaler.fit_transform(df[columns_to_normalize])

print(df)

    order_id  customer_id            brand              model  \
0   0.000000     0.921569  Paul Reed Smith          Custom 22   
1   0.052632     0.745098           Fender       Stratocaster   
2   0.105263     0.686275           Gibson  Les Paul Standard   
3   0.157895     0.862745           Ibanez        SA460QM-ABB   
4   0.210526     0.156863          Jackson              Dinky   
5   0.263158     1.000000         Schecter         Hellraiser   
6   0.315789     0.137255          Epihone                Dot   
7   0.368421     0.000000     Rickenbacker       Model 330 12   
8   0.421053     0.627451              G&L          Fullerton   
9   0.473684     0.803922          Charvel            Pro-Mod   
10  0.526316     0.509804           Fender       Stratocaster   
11  0.578947     0.352941           Fender       Stratocaster   
12  0.631579     0.274510          Epihone                Dot   
13  0.684211     0.235294  Paul Reed Smith                 SE   
14  0.736842     0.294118

In [15]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.feature_selection import SelectKBest, f_classif, SelectFromModel, RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Generate sample data
X, y = make_classification(n_samples=1000, n_features=20, n_informative=10, n_redundant=5, random_state=42)

# Univariate Feature Selection (SelectKBest with ANOVA F-test)
k = 10  # number of top features to select
selector = SelectKBest(score_func=f_classif, k=k)
X_new_univariate = selector.fit_transform(X, y)

# Tree-based Feature Selection (SelectFromModel with Random Forest)
clf = RandomForestClassifier(n_estimators=100, random_state=42)
selector = SelectFromModel(clf)
X_new_tree_based = selector.fit_transform(X, y)

# Greedy Feature Selection (RFE with Logistic Regression)
estimator = LogisticRegression(max_iter=1000, random_state=42)
selector = RFE(estimator, n_features_to_select=k)
X_new_greedy = selector.fit_transform(X, y)

# Print the selected features for each method
print("Selected features using Univariate Feature Selection:")
print(selector.get_support(indices=True))

print("Selected features using Tree-based Feature Selection:")
print(selector.get_support(indices=True))

print("Selected features using Greedy Feature Selection:")
print(selector.get_support(indices=True))


Selected features using Univariate Feature Selection:
[ 0  1  2  3  5  7 11 14 15 17]
Selected features using Tree-based Feature Selection:
[ 0  1  2  3  5  7 11 14 15 17]
Selected features using Greedy Feature Selection:
[ 0  1  2  3  5  7 11 14 15 17]


In [16]:
import pandas as pd
import numpy as np

# Create a sample dataset with outliers
data = {
    'EmployeeID': range(1, 101),
    'DailyRate': np.random.randint(100, 500, size=100)  # Generating random DailyRate values
}
data['DailyRate'][0] = 2000  # Introducing an outlier

# Creating DataFrame
df = pd.DataFrame(data)

# Identifying and handling outliers
columns_with_outliers = ['DailyRate']

for c in columns_with_outliers:
    transform = 'clipped_' + c
    lower_limit = df[c].quantile(0.10)
    upper_limit = df[c].quantile(0.90)
    df[transform] = df[c].clip(lower_limit, upper_limit)

# Displaying the original and transformed DataFrame
print("Original DataFrame:")
print(df.head())

# Showing clipped values
print("\nTransformed DataFrame with clipped values:")
print(df[['DailyRate', 'clipped_DailyRate']].head())


Original DataFrame:
   EmployeeID  DailyRate  clipped_DailyRate
0           1       2000              473.4
1           2        355              355.0
2           3        302              302.0
3           4        319              319.0
4           5        360              360.0

Transformed DataFrame with clipped values:
   DailyRate  clipped_DailyRate
0       2000              473.4
1        355              355.0
2        302              302.0
3        319              319.0
4        360              360.0


In [17]:
import pandas as pd
import numpy as np

In [18]:
usedCars = pd.read_csv("used cars.csv") #returns dataframe

In [19]:
usedCars.head()

Unnamed: 0                              Name    Location  Year  \
0           1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015   
1           2                      Honda Jazz V     Chennai  2011   
2           3                 Maruti Ertiga VDI     Chennai  2012   
3           4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013   
4           6            Nissan Micra Diesel XV      Jaipur  2013   

   Kilometers_Driven Fuel_Type Transmission Owner_Type     Mileage   Engine  \
0              41000    Diesel       Manual      First  19.67 kmpl  1582 CC   
1              46000    Petrol       Manual      First    13 km/kg  1199 CC   
2              87000    Diesel       Manual      First  20.77 kmpl  1248 CC   
3              40670    Diesel    Automatic     Second   15.2 kmpl  1968 CC   
4              86999    Diesel       Manual      First  23.08 kmpl  1461 CC   

       Power  Seats  New_Price  Price  
0  126.2 bhp    5.0        NaN  12.50  
1   88.7 bhp    5.0  8.61 Lakh   4.50  
2  88.76 bhp    7.0        NaN   6.00  
3  140.8 bhp    5.0        NaN  17.74  
4   63.1 bhp    5.0        NaN   3.50